name: Node.js CI

on:
  push:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2 #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 #  # Reference a specific version
      with:
        node-version: ${{ matrix.node-version }}  #use node version which define above
        cache: 'npm'
        run: npm install
    - run: |
          git clone "https://github.com/Samyakt24/LearnGit.git"
          cd LearnGit
          git config --global user.email "samyaktjain1999@gmail.com"
          git config --global user.name "Samyakt24"
        
          
    - run: |
          git clone "https://github.com/Samyakt24/ManNode.git"
          cd ManNode
          npm version 1.1.1
          git add package.json
          git commit package.json -m "package.json commit"
          npm 1.1.2 patch --no-git-tag-version
          git add package.json
          git commit package.json -m "package.json commit"
          git checkout main
          git pull
          git push --force origin main
