# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Github Actions Examples
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testing Git

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm update
      run: npx npm-check-updates -u
    - name: npm installation
      run: npm install
    - name: set email
      run: git config --global user.email "samyaktjain1999@gmail.com"
    - name: set name
      run:   git config --global user.name "Samyakt24"
    - name: packet json commit
      run: git commit package.json -m "Commit"
    - name: setup Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7.7' # install the python version needed
          
    - name: import os module
      run: import os
    - name: change directory
      run: os.chdir(Samyakt24/NODEPRO/public)
    - name: list the file
      run: ls  
